// AUTO-GENERATED by scripts/generate-seo-layouts.js — edit src/lib/seo.ts instead.
import type { Metadata } from 'next';
import { toolMetadata } from '@/lib/seo';
import { ToolJsonLd } from '@/components/seo/ToolJsonLd';

export const metadata: Metadata = toolMetadata('office-to-pdf');

export default function SeoLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
            {children}
            <ToolJsonLd toolKey="office-to-pdf" />
        </>
    );
}
